name: selam
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  random_string: ^2.3.1
  fluttertoast: ^8.2.4
  flutter_slidable: ^3.0.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9
  firebase_auth: ^5.2.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  image_picker: ^1.0.7
  firebase_storage: ^12.2.0
  stylish_bottom_bar: ^1.0.3
  loading_animation_widget: ^1.2.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  grouped_list: ^6.0.0
  intl: ^0.19.0
  xid: ^1.1.2
  timeago: ^3.0.2
  intl_phone_field: ^3.2.0
  motion_tab_bar_v2: ^0.3.0
  flutter_swiper_view: ^1.1.8
  http: ^1.1.0
  permission_handler: ^11.0.0
  crystal_navigation_bar: ^1.0.2
  firebase_messaging: ^15.1.0
  font_awesome_flutter: ^10.8.0
  flutter_screen_lock: ^9.0.4
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.0
  carousel_slider: ^5.0.0
  photo_manager: ^3.6.4
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 300
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
